create database moments


CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT,
  email VARCHAR(200) NOT NULL,
  senha VARCHAR(200) NOT NULL,
  nome VARCHAR(200) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (email)
);

CREATE TABLE EMAIL_USUARIO_SUCCESS (
  id INT NOT NULL AUTO_INCREMENT,
  emailId VARCHAR(200) NOT NULL,
  STATUS VARCHAR(20)
  PRIMARY KEY (id),
  UNIQUE KEY (email)
);


CREATE TABLE Foto (
  id INT NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(255) NOT NULL,
  data DATE NOT NULL,
  localizacao VARCHAR(255) NOT NULL,
  descricao VARCHAR(255),
  PRIMARY KEY (foto_id)
);


CREATE TABLE Album (
  id INT NOT NULL AUTO_INCREMENT,
  nome_Album VARCHAR(255) NOT NULL,
  descricao VARCHAR(255),
  data_criacao DATE NOT NULL,
  PRIMARY KEY (id)
);